### ISSUE TITLE
OFS introduce true compression

### ISSUE THREAD

**Issue by TheAio** [TheAio/CCTills#4]
OFS introduce true compression, currently OFS does what it was designed to do perfectly and includes some "compressive" features via alib. But no matter what you do the size of output files from OFS will **always** be bigger then the input, and in fact this issue gets worse with the "compressive" modes as they were not design to compress the file but rather transform them into files that are easier to modify.

It would perhaps be a good idea as i have discussed a little bit with @XDuskAshes about, to introduce true compression in OFS.
I was thinking that we perhaps should use [Huffman coding](https://en.wikipedia.org/wiki/Huffman_coding) for the compression algorithm, since it is pretty effective at larger files such as a OFS file. There are 3 questions that i have first tho.

- [x] Should we use Huffman coding?
- [ ] If we do use Huffman coding, how should we store the translation tree?
- [x] Should the compression algorithm we pick be part of alib so it can be used by other software easier or native to OFS?

**Comment by XDuskAshes** [comment]
@TheAio this is a good idea, and I think we should use it too.
Also probably do both alib and OFS natively, with alib being more extensive and OFS being just for OFS

**Comment by TheAio** [comment]
Im going to assume we will store the translation file inside the compressed file then because it would be more convenient.
Not entirely sure how we should build the translation tree in code, but i guess we will figure it out as we go :)

**Comment by TheAio** [comment]
I have a possible better idea then OFS all together,
i will consider the idea and write a demo. If the demo works ill release it here,
for now im closing this issue as "not planned" since its stale and i have a possible replacement idea.
We can of course open this issue again if requested and/or more progress is made.
