### ISSUE TITLE
Util to replace the BIOS with a custom one?

### ISSUE THREAD

**Issue by XDuskAshes** [TheAio/CCTills#5]
Basically, an UnBIOS grabber that can also grab a ``bios.lua`` image as supplied.

I'll work on this when I can.

**Comment by TheAio** [comment]
That would likely be a good addition to the repository, ill also begin work on it as soon as i have time to do so.
Perhaps we could make our own UnBIOS rather then depend on the official software?

**Comment by XDuskAshes** [comment]
> Perhaps we could make our own UnBIOS rather then depend on the official software?

Perhaps. It is under the MIT license though, so we could theoretically relicense everything here accordingly, or deal with SPDX messery. I think we should go with MIT relicensing, given that we have the copyrights to our respective utils and can do that at our discretion. Also, MIT license is just kinda better for open source projects such as this, if you ask me.

**Comment by XDuskAshes** [comment]
Additionally, lets do a little example of the syntax idea
lets call the tool.. uuuuh- just temporarily, ``bioser`` (pulled it right out where the sun dont shine)

Usual usage:
```
bioser <link to custom bios> <possible options>
```

Help:
```
bioser <-h/--help>
```
Note: Could also do something like having no args display the help message with an extra line like, "Cannot accept no args, showing help."

Example help message:
```
bioser - CraftOS BIOS replacer.
Usage:
 bioser <link to custom bios> <optional args>
Args:
-v/--verbose - Be verbose with output.
-l/--log <logfile> - Output a log file at the designated location.
```
@TheAio

**Comment by TheAio** [comment]
work as begun on this issue in private, away from github.
@XDuskAshes check dms :)
We can upload it as foss when its closer to being done.
